### ISSUE TITLE
Missing refine_result file for event_train.py

### ISSUE THREAD

**Issue by bernardoacalvo** [ZILIN003/CAMEL#2]
Hi, could you please share the refine_result file? 
I need it to reproduce the evaluation pipeline.
While it is referenced in a previous work, it differs from what you have implemented in your code.
Thanks in advance.

**Comment by JJFORJEY** [comment]
Hi, I have the same question

**Comment by ZILIN003** [comment]
Thanks for your interests. I have uploaded two files.

**Comment by JJFORJEY** [comment]
Thanks for your reply！
